# Generated by Django 4.0.3 on 2023-06-22 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseinput',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parseinput',
            name='time_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
