# Generated by Django 4.0.3 on 2023-06-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0002_parseinput_time_created_parseinput_time_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseinput',
            name='p_output',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
