# Generated by Django 4.2.2 on 2023-06-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0004_alter_parseinput_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseinput',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
