# Generated by Django 4.0.3 on 2023-06-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0005_alter_parseinput_time_created'),
        ('parserAPI', '0005_parseinput_ticket_number'),
    ]

    operations = [
    ]
