# Generated by Django 4.0.3 on 2023-06-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0006_merge_20230628_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseinput',
            name='time_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
