# Generated by Django 4.0.3 on 2023-06-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0007_alter_parseinput_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseinput',
            name='client_ip',
            field=models.CharField(default='0.0.0.0', max_length=50),
            preserve_default=False,
        ),
    ]
