# Generated by Django 4.2.2 on 2023-06-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0006_merge_20230628_2049'),
        ('parserAPI', '0008_parseinput_client_ip'),
    ]

    operations = [
    ]
