# Generated by Django 4.0.3 on 2023-07-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0009_merge_20230629_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parseinput',
            name='p_input',
        ),
        migrations.AlterField(
            model_name='parseinput',
            name='p_output',
            field=models.JSONField(null=True),
        ),
    ]
