# Generated by Django 4.0.3 on 2023-07-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0010_remove_parseinput_p_input_alter_parseinput_p_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseinput',
            name='filename',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parseinput',
            name='parser',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
