# Generated by Django 4.2.2 on 2023-07-03 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0009_alter_parseinput_p_output'),
        ('parserAPI', '0011_parseinput_filename_parseinput_parser'),
    ]

    operations = [
    ]
