# Generated by Django 4.0.3 on 2023-07-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0011_parseinput_filename_parseinput_parser'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseinput',
            name='file_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
