# Generated by Django 4.0.3 on 2023-07-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0012_parseinput_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseinput',
            name='file_content',
            field=models.FileField(upload_to=''),
        ),
    ]
