# Generated by Django 4.0.3 on 2023-07-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0014_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseinput',
            name='file_content',
            field=models.CharField(max_length=500),
        ),
    ]
