# Generated by Django 4.0.3 on 2023-07-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0017_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parseinput',
            name='filename',
        ),
    ]
