# Generated by Django 4.0.3 on 2023-07-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0018_remove_parseinput_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parseinput',
            name='file',
        ),
    ]
