# Generated by Django 4.0.3 on 2023-07-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0019_remove_parseinput_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parseinput',
            name='file_content',
        ),
    ]
