# Generated by Django 4.0.3 on 2023-07-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0020_remove_parseinput_file_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parseinput',
            name='p_output',
        ),
    ]
