# Generated by Django 4.0.3 on 2023-07-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0021_remove_parseinput_p_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='parseinput',
            name='file_content',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
