# Generated by Django 4.0.3 on 2023-07-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0023_parseinput_p_output_alter_parseinput_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseinput',
            name='p_output',
            field=models.CharField(default='', max_length=4000),
            preserve_default=False,
        ),
    ]
