# Generated by Django 4.2.2 on 2023-07-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0012_merge_20230703_1821'),
        ('parserAPI', '0024_alter_parseinput_p_output'),
    ]

    operations = [
    ]
