# Generated by Django 4.0.3 on 2023-07-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0025_alter_parseinput_file_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseinput',
            name='file_content',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='parseinput',
            name='p_output',
            field=models.CharField(max_length=1000000),
        ),
    ]
