# Generated by Django 4.2.2 on 2023-07-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0025_merge_20230710_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseinput',
            name='p_output',
            field=models.CharField(max_length=4000),
        ),
    ]
