# Generated by Django 4.2.2 on 2023-07-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0027_alter_parseinput_p_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseinput',
            name='p_output',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
