# Generated by Django 4.2.2 on 2023-07-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0029_alter_parseinput_p_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parseinput',
            name='file_content',
        ),
    ]
