# Generated by Django 4.2.2 on 2023-07-13 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0030_remove_parseinput_file_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.IntegerField()),
                ('parser', models.CharField(max_length=50)),
                ('status', models.CharField(default='Starting', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(max_length=50)),
                ('time_created', models.DateTimeField(blank=True, null=True)),
                ('time_finished', models.DateTimeField(blank=True, null=True)),
                ('parser', models.CharField(max_length=50)),
                ('p_output', models.JSONField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parserAPI.ticket')),
            ],
        ),
    ]
