# Generated by Django 4.2.2 on 2023-07-19 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0030_remove_parseinput_file_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_number', models.IntegerField(primary_key=True, serialize=False)),
                ('parser', models.CharField(max_length=100)),
                ('status', models.CharField(default='Starting', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField()),
                ('time_finished', models.DateTimeField()),
                ('p_output', models.JSONField()),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_fields', to='parserAPI.ticket')),
            ],
        ),
    ]
