# Generated by Django 4.2.2 on 2023-07-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0031_ticket_additionalfields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='parseInput',
        ),
    ]
