# Generated by Django 4.2.2 on 2023-07-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0032_delete_parseinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='parser',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
