# Generated by Django 4.0.3 on 2023-07-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0033_alter_ticket_parser_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalTicket',
            fields=[
                ('ticket_number', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('parser', models.CharField(default='unknown', max_length=100)),
                ('client_ip', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField()),
                ('time_finished', models.DateTimeField()),
                ('p_output', models.JSONField()),
            ],
        ),
    ]
