# Generated by Django 4.2.2 on 2023-07-26 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0033_alter_ticket_parser_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalfields',
            name='client_ip',
        ),
    ]
