# Generated by Django 4.0.3 on 2023-07-21 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0034_finalticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalticket',
            name='ticket_number',
        ),
        migrations.AddField(
            model_name='finalticket',
            name='first_ticket',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='FinalTicket', to='parserAPI.ticket'),
        ),
        migrations.AddField(
            model_name='finalticket',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
