# Generated by Django 4.0.3 on 2023-07-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0035_remove_finalticket_ticket_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalticket',
            name='parser',
        ),
    ]
