# Generated by Django 4.0.3 on 2023-07-21 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0036_remove_finalticket_parser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalticket',
            name='first_ticket',
        ),
        migrations.AddField(
            model_name='finalticket',
            name='parser',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='finalticket',
            name='ticket',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='final_tick', to='parserAPI.ticket'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdditionalFields',
        ),
    ]
