# Generated by Django 4.0.3 on 2023-07-21 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parserAPI', '0037_remove_finalticket_first_ticket_finalticket_parser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalticket',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_fields', to='parserAPI.ticket'),
        ),
    ]
